//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_inventario_Entities : DbContext
    {
        public db_inventario_Entities()
            : base("name=db_inventario_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Cajas> Tbl_Cajas { get; set; }
    
        public virtual ObjectResult<rpt_poliza_ventas_posFEL_Result> rpt_poliza_ventas_posFEL(Nullable<int> id_Empresa, Nullable<int> id_caja, Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final, Nullable<int> tipo_reporte, string tipo_poliza, string numero_poliza)
        {
            var id_EmpresaParameter = id_Empresa.HasValue ?
                new ObjectParameter("Id_Empresa", id_Empresa) :
                new ObjectParameter("Id_Empresa", typeof(int));
    
            var id_cajaParameter = id_caja.HasValue ?
                new ObjectParameter("Id_caja", id_caja) :
                new ObjectParameter("Id_caja", typeof(int));
    
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("Fecha_inicial", fecha_inicial) :
                new ObjectParameter("Fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("Fecha_final", fecha_final) :
                new ObjectParameter("Fecha_final", typeof(System.DateTime));
    
            var tipo_reporteParameter = tipo_reporte.HasValue ?
                new ObjectParameter("Tipo_reporte", tipo_reporte) :
                new ObjectParameter("Tipo_reporte", typeof(int));
    
            var tipo_polizaParameter = tipo_poliza != null ?
                new ObjectParameter("Tipo_poliza", tipo_poliza) :
                new ObjectParameter("Tipo_poliza", typeof(string));
    
            var numero_polizaParameter = numero_poliza != null ?
                new ObjectParameter("Numero_poliza", numero_poliza) :
                new ObjectParameter("Numero_poliza", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_poliza_ventas_posFEL_Result>("rpt_poliza_ventas_posFEL", id_EmpresaParameter, id_cajaParameter, fecha_inicialParameter, fecha_finalParameter, tipo_reporteParameter, tipo_polizaParameter, numero_polizaParameter);
        }
    
        public virtual ObjectResult<sp_verificarTraslados_Result> sp_verificarTraslados(Nullable<int> id_empresa, string anio, string mes, string tipo, string caja)
        {
            var id_empresaParameter = id_empresa.HasValue ?
                new ObjectParameter("id_empresa", id_empresa) :
                new ObjectParameter("id_empresa", typeof(int));
    
            var anioParameter = anio != null ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var cajaParameter = caja != null ?
                new ObjectParameter("caja", caja) :
                new ObjectParameter("caja", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_verificarTraslados_Result>("sp_verificarTraslados", id_empresaParameter, anioParameter, mesParameter, tipoParameter, cajaParameter);
        }
    
        public virtual ObjectResult<rpt_poliza_ventas_posFEL1_Result> rpt_poliza_ventas_posFEL1(Nullable<int> id_Empresa, Nullable<int> id_caja, Nullable<System.DateTime> fecha_inicial, Nullable<System.DateTime> fecha_final, Nullable<int> tipo_reporte, string tipo_poliza, string numero_poliza)
        {
            var id_EmpresaParameter = id_Empresa.HasValue ?
                new ObjectParameter("Id_Empresa", id_Empresa) :
                new ObjectParameter("Id_Empresa", typeof(int));
    
            var id_cajaParameter = id_caja.HasValue ?
                new ObjectParameter("Id_caja", id_caja) :
                new ObjectParameter("Id_caja", typeof(int));
    
            var fecha_inicialParameter = fecha_inicial.HasValue ?
                new ObjectParameter("Fecha_inicial", fecha_inicial) :
                new ObjectParameter("Fecha_inicial", typeof(System.DateTime));
    
            var fecha_finalParameter = fecha_final.HasValue ?
                new ObjectParameter("Fecha_final", fecha_final) :
                new ObjectParameter("Fecha_final", typeof(System.DateTime));
    
            var tipo_reporteParameter = tipo_reporte.HasValue ?
                new ObjectParameter("Tipo_reporte", tipo_reporte) :
                new ObjectParameter("Tipo_reporte", typeof(int));
    
            var tipo_polizaParameter = tipo_poliza != null ?
                new ObjectParameter("Tipo_poliza", tipo_poliza) :
                new ObjectParameter("Tipo_poliza", typeof(string));
    
            var numero_polizaParameter = numero_poliza != null ?
                new ObjectParameter("Numero_poliza", numero_poliza) :
                new ObjectParameter("Numero_poliza", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rpt_poliza_ventas_posFEL1_Result>("rpt_poliza_ventas_posFEL1", id_EmpresaParameter, id_cajaParameter, fecha_inicialParameter, fecha_finalParameter, tipo_reporteParameter, tipo_polizaParameter, numero_polizaParameter);
        }
    
        public virtual ObjectResult<sp_getEmpresas_Result> sp_getEmpresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getEmpresas_Result>("sp_getEmpresas");
        }
    }
}
